use LMCdatabase
go

-- Testing values
-- tblPostNo
Insert into [dbo].[tblPostNo] values(2000, 'Frederiksberg');
Insert into [dbo].[tblPostNo] values(2100, 'København Ø');
Insert into [dbo].[tblPostNo] values(2200, 'København N');
Insert into [dbo].[tblPostNo] values(2300, 'København S');
Insert into [dbo].[tblPostNo] values(2400, 'København NV');
Insert into [dbo].[tblPostNo] values(2450, 'København SV');
Insert into [dbo].[tblPostNo] values(2500, 'Valby');
Insert into [dbo].[tblPostNo] values(2600, 'Glostrup');
Insert into [dbo].[tblPostNo] values(2605, 'Brøndby');
Insert into [dbo].[tblPostNo] values(2610, 'Rødovre');
Insert into [dbo].[tblPostNo] values(2620, 'Albertslund');
Insert into [dbo].[tblPostNo] values(2625, 'Vallensbæk');
Insert into [dbo].[tblPostNo] values(2630, 'Taastrup');
Insert into [dbo].[tblPostNo] values(2633, 'Taastrup Nordsjællands Postcenter');
Insert into [dbo].[tblPostNo] values(2635, 'Ishøj');
Insert into [dbo].[tblPostNo] values(2640, 'Hedehusene');
Insert into [dbo].[tblPostNo] values(2650, 'Hvidovre');
Insert into [dbo].[tblPostNo] values(2660, 'Brøndby Strand');
Insert into [dbo].[tblPostNo] values(2665, 'Vallensbæk Strand');
Insert into [dbo].[tblPostNo] values(2670, 'Greve');
Insert into [dbo].[tblPostNo] values(2680, 'Solrød Strand');
Insert into [dbo].[tblPostNo] values(2690, 'Karlslunde');
Insert into [dbo].[tblPostNo] values(2700, 'Brønshøj');
Insert into [dbo].[tblPostNo] values(2720, 'Vanløse');
Insert into [dbo].[tblPostNo] values(2730, 'Herlev');
Insert into [dbo].[tblPostNo] values(2740, 'Skovlunde');
Insert into [dbo].[tblPostNo] values(2750, 'Ballerup');
Insert into [dbo].[tblPostNo] values(2760, 'Måløv');
Insert into [dbo].[tblPostNo] values(2765, 'Smørum');
Insert into [dbo].[tblPostNo] values(2770, 'Kastrup');
Insert into [dbo].[tblPostNo] values(2791, 'Dragør');
Insert into [dbo].[tblPostNo] values(2800, 'Kongens Lyngby');
Insert into [dbo].[tblPostNo] values(2820, 'Gentofte');
Insert into [dbo].[tblPostNo] values(2830, 'Virum');
Insert into [dbo].[tblPostNo] values(2840, 'Holte');
Insert into [dbo].[tblPostNo] values(2850, 'Nærum');
Insert into [dbo].[tblPostNo] values(2860, 'Søborg');
Insert into [dbo].[tblPostNo] values(2870, 'Dyssegård');
Insert into [dbo].[tblPostNo] values(2880, 'Bagsværd');
Insert into [dbo].[tblPostNo] values(2900, 'Hellerup');
Insert into [dbo].[tblPostNo] values(2920, 'Charlottenlund');
Insert into [dbo].[tblPostNo] values(2930, 'Klampenborg');
Insert into [dbo].[tblPostNo] values(2942, 'Skodsborg');
Insert into [dbo].[tblPostNo] values(2950, 'Vedbæk');
Insert into [dbo].[tblPostNo] values(2960, 'Rungsted Kyst');
Insert into [dbo].[tblPostNo] values(2970, 'Hørsholm');
Insert into [dbo].[tblPostNo] values(2980, 'Kokkedal');
Insert into [dbo].[tblPostNo] values(2990, 'Nivå');
Insert into [dbo].[tblPostNo] values(3000, 'Helsingør');
Insert into [dbo].[tblPostNo] values(3050, 'Humlebæk');
Insert into [dbo].[tblPostNo] values(3060, 'Espergærde');
Insert into [dbo].[tblPostNo] values(3070, 'Snekkersten');
Insert into [dbo].[tblPostNo] values(3080, 'Tikøb');
Insert into [dbo].[tblPostNo] values(3100, 'Hornbæk');
Insert into [dbo].[tblPostNo] values(3120, 'Dronningmølle');
Insert into [dbo].[tblPostNo] values(3140, 'Ålsgårde');
Insert into [dbo].[tblPostNo] values(3150, 'Hellebæk');
Insert into [dbo].[tblPostNo] values(3200, 'Helsinge');
Insert into [dbo].[tblPostNo] values(3210, 'Vejby');
Insert into [dbo].[tblPostNo] values(3220, 'Tisvildeleje');
Insert into [dbo].[tblPostNo] values(3230, 'Græsted');
Insert into [dbo].[tblPostNo] values(3250, 'Gilleleje');
Insert into [dbo].[tblPostNo] values(3300, 'Frederiksværk');
Insert into [dbo].[tblPostNo] values(3310, 'Ølsted');
Insert into [dbo].[tblPostNo] values(3320, 'Skævinge');
Insert into [dbo].[tblPostNo] values(3330, 'Gørløse');
Insert into [dbo].[tblPostNo] values(3360, 'Liseleje');
Insert into [dbo].[tblPostNo] values(3370, 'Melby');
Insert into [dbo].[tblPostNo] values(3390, 'Hundested');
Insert into [dbo].[tblPostNo] values(3400, 'Hillerød');
Insert into [dbo].[tblPostNo] values(3450, 'Allerød');
Insert into [dbo].[tblPostNo] values(3460, 'Birkerød');
Insert into [dbo].[tblPostNo] values(3480, 'Fredensborg');
Insert into [dbo].[tblPostNo] values(3490, 'Kvistgård');
Insert into [dbo].[tblPostNo] values(3500, 'Værløse');
Insert into [dbo].[tblPostNo] values(3520, 'Farum');
Insert into [dbo].[tblPostNo] values(3540, 'Lynge');
Insert into [dbo].[tblPostNo] values(3550, 'Slangerup');
Insert into [dbo].[tblPostNo] values(3600, 'Frederikssund');
Insert into [dbo].[tblPostNo] values(3630, 'Jægerspris');
Insert into [dbo].[tblPostNo] values(3650, 'Ølstykke');
Insert into [dbo].[tblPostNo] values(3660, 'Stenløse');
Insert into [dbo].[tblPostNo] values(3670, 'Veksø Sjælland');
Insert into [dbo].[tblPostNo] values(3700, 'Rønne');
Insert into [dbo].[tblPostNo] values(3720, 'Aakirkeby');
Insert into [dbo].[tblPostNo] values(3730, 'Nexø');
Insert into [dbo].[tblPostNo] values(3740, 'Svaneke');
Insert into [dbo].[tblPostNo] values(3751, 'Østermarie');
Insert into [dbo].[tblPostNo] values(3760, 'Gudhjem');
Insert into [dbo].[tblPostNo] values(3770, 'Allinge');
Insert into [dbo].[tblPostNo] values(3782, 'Klemensker');
Insert into [dbo].[tblPostNo] values(3790, 'Hasle');
Insert into [dbo].[tblPostNo] values(4000, 'Roskilde');
Insert into [dbo].[tblPostNo] values(4040, 'Jyllinge');
Insert into [dbo].[tblPostNo] values(4050, 'Skibby');
Insert into [dbo].[tblPostNo] values(4060, 'Kirke Såby');
Insert into [dbo].[tblPostNo] values(4070, 'Kirke Hyllinge');
Insert into [dbo].[tblPostNo] values(4100, 'Ringsted');
Insert into [dbo].[tblPostNo] values(4105, 'Ringsted Midtsjællands Postcenter');
Insert into [dbo].[tblPostNo] values(4130, 'Viby Sjælland');
Insert into [dbo].[tblPostNo] values(4140, 'Borup');
Insert into [dbo].[tblPostNo] values(4160, 'Herlufmagle');
Insert into [dbo].[tblPostNo] values(4171, 'Glumsø');
Insert into [dbo].[tblPostNo] values(4173, 'Fjenneslev');
Insert into [dbo].[tblPostNo] values(4174, 'Jystrup Midtsjælland');
Insert into [dbo].[tblPostNo] values(4180, 'Sorø');
Insert into [dbo].[tblPostNo] values(4190, 'Munke Bjergby');
Insert into [dbo].[tblPostNo] values(4200, 'Slagelse');
Insert into [dbo].[tblPostNo] values(4220, 'Korsør');
Insert into [dbo].[tblPostNo] values(4230, 'Skælskør');
Insert into [dbo].[tblPostNo] values(4241, 'Vemmelev');
Insert into [dbo].[tblPostNo] values(4242, 'Boeslunde');
Insert into [dbo].[tblPostNo] values(4243, 'Rude');
Insert into [dbo].[tblPostNo] values(4250, 'Fuglebjerg');
Insert into [dbo].[tblPostNo] values(4261, 'Dalmose');
Insert into [dbo].[tblPostNo] values(4262, 'Sandved');
Insert into [dbo].[tblPostNo] values(4270, 'Høng');
Insert into [dbo].[tblPostNo] values(4281, 'Gørlev');
Insert into [dbo].[tblPostNo] values(4291, 'Ruds Vedby');
Insert into [dbo].[tblPostNo] values(4293, 'Dianalund');
Insert into [dbo].[tblPostNo] values(4295, 'Stenlille');
Insert into [dbo].[tblPostNo] values(4296, 'Nyrup');
Insert into [dbo].[tblPostNo] values(4300, 'Holbæk');
Insert into [dbo].[tblPostNo] values(4320, 'Lejre');
Insert into [dbo].[tblPostNo] values(4330, 'Hvalsø');
Insert into [dbo].[tblPostNo] values(4340, 'Tølløse');
Insert into [dbo].[tblPostNo] values(4350, 'Ugerløse');
Insert into [dbo].[tblPostNo] values(4360, 'Kirke Eskilstrup');
Insert into [dbo].[tblPostNo] values(4370, 'Store Merløse');
Insert into [dbo].[tblPostNo] values(4390, 'Vipperød');
Insert into [dbo].[tblPostNo] values(4400, 'Kalundborg');
Insert into [dbo].[tblPostNo] values(4420, 'Regstrup');
Insert into [dbo].[tblPostNo] values(4440, 'Mørkøv');
Insert into [dbo].[tblPostNo] values(4450, 'Jyderup');
Insert into [dbo].[tblPostNo] values(4460, 'Snertinge');
Insert into [dbo].[tblPostNo] values(4470, 'Svebølle');
Insert into [dbo].[tblPostNo] values(4480, 'Store Fuglede');
Insert into [dbo].[tblPostNo] values(4490, 'Jerslev Sjælland');
Insert into [dbo].[tblPostNo] values(4500, 'Nykøbing Sjælland');
Insert into [dbo].[tblPostNo] values(4520, 'Svinninge');
Insert into [dbo].[tblPostNo] values(4532, 'Gislinge');
Insert into [dbo].[tblPostNo] values(4534, 'Hørve');
Insert into [dbo].[tblPostNo] values(4540, 'Fårevejle');
Insert into [dbo].[tblPostNo] values(4550, 'Asnæs');
Insert into [dbo].[tblPostNo] values(4560, 'Vig');
Insert into [dbo].[tblPostNo] values(4571, 'Grevinge');
Insert into [dbo].[tblPostNo] values(4572, 'Nørre Asmindrup');
Insert into [dbo].[tblPostNo] values(4573, 'Højby');
Insert into [dbo].[tblPostNo] values(4581, 'Rørvig');
Insert into [dbo].[tblPostNo] values(4583, 'Sjællands Odde');
Insert into [dbo].[tblPostNo] values(4591, 'Føllenslev');
Insert into [dbo].[tblPostNo] values(4592, 'Sejerø');
Insert into [dbo].[tblPostNo] values(4593, 'Eskebjerg');
Insert into [dbo].[tblPostNo] values(4600, 'Køge');
Insert into [dbo].[tblPostNo] values(4621, 'Gadstrup');
Insert into [dbo].[tblPostNo] values(4622, 'Havdrup');
Insert into [dbo].[tblPostNo] values(4623, 'Lille Skensved');
Insert into [dbo].[tblPostNo] values(4632, 'Bjæverskov');
Insert into [dbo].[tblPostNo] values(4640, 'Fakse');
Insert into [dbo].[tblPostNo] values(4652, 'Hårlev');
Insert into [dbo].[tblPostNo] values(4653, 'Karise');
Insert into [dbo].[tblPostNo] values(4654, 'Fakse Ladeplads');
Insert into [dbo].[tblPostNo] values(4660, 'Store Heddinge');
Insert into [dbo].[tblPostNo] values(4671, 'Strøby');
Insert into [dbo].[tblPostNo] values(4672, 'Klippinge');
Insert into [dbo].[tblPostNo] values(4673, 'Rødvig Stevns');
Insert into [dbo].[tblPostNo] values(4681, 'Herfølge');
Insert into [dbo].[tblPostNo] values(4682, 'Tureby');
Insert into [dbo].[tblPostNo] values(4683, 'Rønnede');
Insert into [dbo].[tblPostNo] values(4684, 'Holmegaard');
Insert into [dbo].[tblPostNo] values(4690, 'Haslev');
Insert into [dbo].[tblPostNo] values(4700, 'Næstved');
Insert into [dbo].[tblPostNo] values(4720, 'Præstø');
Insert into [dbo].[tblPostNo] values(4733, 'Tappernøje');
Insert into [dbo].[tblPostNo] values(4735, 'Mern');
Insert into [dbo].[tblPostNo] values(4736, 'Karrebæksminde');
Insert into [dbo].[tblPostNo] values(4750, 'Lundby');
Insert into [dbo].[tblPostNo] values(4760, 'Vordingborg');
Insert into [dbo].[tblPostNo] values(4771, 'Kalvehave');
Insert into [dbo].[tblPostNo] values(4772, 'Langebæk');
Insert into [dbo].[tblPostNo] values(4773, 'Stensved');
Insert into [dbo].[tblPostNo] values(4780, 'Stege');
Insert into [dbo].[tblPostNo] values(4791, 'Borre');
Insert into [dbo].[tblPostNo] values(4792, 'Askeby');
Insert into [dbo].[tblPostNo] values(4793, 'Bogø By');
Insert into [dbo].[tblPostNo] values(4800, 'Nykøbing Falster');
Insert into [dbo].[tblPostNo] values(4840, 'Nørre Alslev');
Insert into [dbo].[tblPostNo] values(4850, 'Stubbekøbing');
Insert into [dbo].[tblPostNo] values(4862, 'Guldborg');
Insert into [dbo].[tblPostNo] values(4863, 'Eskilstrup');
Insert into [dbo].[tblPostNo] values(4871, 'Horbelev');
Insert into [dbo].[tblPostNo] values(4872, 'Idestrup');
Insert into [dbo].[tblPostNo] values(4873, 'Væggerløse');
Insert into [dbo].[tblPostNo] values(4874, 'Gedser');
Insert into [dbo].[tblPostNo] values(4880, 'Nysted');
Insert into [dbo].[tblPostNo] values(4891, 'Toreby Lolland');
Insert into [dbo].[tblPostNo] values(4892, 'Kettinge');
Insert into [dbo].[tblPostNo] values(4894, 'Øster Ulslev');
Insert into [dbo].[tblPostNo] values(4895, 'Errindlev');
Insert into [dbo].[tblPostNo] values(4900, 'Nakskov');
Insert into [dbo].[tblPostNo] values(4912, 'Harpelunde');
Insert into [dbo].[tblPostNo] values(4913, 'Horslunde');
Insert into [dbo].[tblPostNo] values(4920, 'Søllested');
Insert into [dbo].[tblPostNo] values(4930, 'Maribo');
Insert into [dbo].[tblPostNo] values(4941, 'Bandholm');
Insert into [dbo].[tblPostNo] values(4943, 'Torrig Lolland');
Insert into [dbo].[tblPostNo] values(4944, 'Fejø');
Insert into [dbo].[tblPostNo] values(4951, 'Nørreballe');
Insert into [dbo].[tblPostNo] values(4952, 'Stokkemarke');
Insert into [dbo].[tblPostNo] values(4953, 'Vesterborg');
Insert into [dbo].[tblPostNo] values(4960, 'Holeby');
Insert into [dbo].[tblPostNo] values(4970, 'Rødby');
Insert into [dbo].[tblPostNo] values(4983, 'Dannemare');
Insert into [dbo].[tblPostNo] values(4990, 'Sakskøbing');
Insert into [dbo].[tblPostNo] values(5000, 'Odense C');
Insert into [dbo].[tblPostNo] values(5090, 'Odense C Fyns Postcenter');
Insert into [dbo].[tblPostNo] values(5200, 'Odense V');
Insert into [dbo].[tblPostNo] values(5210, 'Odense NV');
Insert into [dbo].[tblPostNo] values(5220, 'Odense SØ');
Insert into [dbo].[tblPostNo] values(5230, 'Odense M');
Insert into [dbo].[tblPostNo] values(5240, 'Odense NØ');
Insert into [dbo].[tblPostNo] values(5250, 'Odense SV');
Insert into [dbo].[tblPostNo] values(5260, 'Odense S');
Insert into [dbo].[tblPostNo] values(5270, 'Odense N');
Insert into [dbo].[tblPostNo] values(5290, 'Marslev');
Insert into [dbo].[tblPostNo] values(5300, 'Kerteminde');
Insert into [dbo].[tblPostNo] values(5320, 'Agedrup');
Insert into [dbo].[tblPostNo] values(5330, 'Munkebo');
Insert into [dbo].[tblPostNo] values(5350, 'Rynkeby');
Insert into [dbo].[tblPostNo] values(5370, 'Mesinge');
Insert into [dbo].[tblPostNo] values(5380, 'Dalby');
Insert into [dbo].[tblPostNo] values(5390, 'Martofte');
Insert into [dbo].[tblPostNo] values(5400, 'Bogense');
Insert into [dbo].[tblPostNo] values(5450, 'Otterup');
Insert into [dbo].[tblPostNo] values(5462, 'Morud');
Insert into [dbo].[tblPostNo] values(5463, 'Harndrup');
Insert into [dbo].[tblPostNo] values(5464, 'Brenderup Fyn');
Insert into [dbo].[tblPostNo] values(5466, 'Asperup');
Insert into [dbo].[tblPostNo] values(5471, 'Søndersø');
Insert into [dbo].[tblPostNo] values(5474, 'Veflinge');
Insert into [dbo].[tblPostNo] values(5485, 'Skamby');
Insert into [dbo].[tblPostNo] values(5491, 'Blommenslyst');
Insert into [dbo].[tblPostNo] values(5492, 'Vissenbjerg');
Insert into [dbo].[tblPostNo] values(5500, 'Middelfart');
Insert into [dbo].[tblPostNo] values(5540, 'Ullerslev');
Insert into [dbo].[tblPostNo] values(5550, 'Langeskov');
Insert into [dbo].[tblPostNo] values(5560, 'Aarup');
Insert into [dbo].[tblPostNo] values(5580, 'Nørre Aaby');
Insert into [dbo].[tblPostNo] values(5591, 'Gelsted');
Insert into [dbo].[tblPostNo] values(5592, 'Ejby');
Insert into [dbo].[tblPostNo] values(5600, 'Faaborg');
Insert into [dbo].[tblPostNo] values(5610, 'Assens');
Insert into [dbo].[tblPostNo] values(5620, 'Glamsbjerg');
Insert into [dbo].[tblPostNo] values(5631, 'Ebberup');
Insert into [dbo].[tblPostNo] values(5642, 'Millinge');
Insert into [dbo].[tblPostNo] values(5672, 'Broby');
Insert into [dbo].[tblPostNo] values(5683, 'Haarby');
Insert into [dbo].[tblPostNo] values(5690, 'Tommerup');
Insert into [dbo].[tblPostNo] values(5700, 'Svendborg');
Insert into [dbo].[tblPostNo] values(5750, 'Ringe');
Insert into [dbo].[tblPostNo] values(5762, 'Vester Skerninge');
Insert into [dbo].[tblPostNo] values(5771, 'Stenstrup');
Insert into [dbo].[tblPostNo] values(5772, 'Kværndrup');
Insert into [dbo].[tblPostNo] values(5792, 'Årslev');
Insert into [dbo].[tblPostNo] values(5800, 'Nyborg');
Insert into [dbo].[tblPostNo] values(5853, 'Ørbæk');
Insert into [dbo].[tblPostNo] values(5854, 'Gislev');
Insert into [dbo].[tblPostNo] values(5856, 'Ryslinge');
Insert into [dbo].[tblPostNo] values(5863, 'Ferritslev Fyn');
Insert into [dbo].[tblPostNo] values(5871, 'Frørup');
Insert into [dbo].[tblPostNo] values(5874, 'Hesselager');
Insert into [dbo].[tblPostNo] values(5881, 'Skårup Fyn');
Insert into [dbo].[tblPostNo] values(5882, 'Vejstrup');
Insert into [dbo].[tblPostNo] values(5883, 'Oure');
Insert into [dbo].[tblPostNo] values(5884, 'Gudme');
Insert into [dbo].[tblPostNo] values(5892, 'Gudbjerg Sydfyn');
Insert into [dbo].[tblPostNo] values(5900, 'Rudkøbing');
Insert into [dbo].[tblPostNo] values(5932, 'Humble');
Insert into [dbo].[tblPostNo] values(5935, 'Bagenkop');
Insert into [dbo].[tblPostNo] values(5953, 'Tranekær');
Insert into [dbo].[tblPostNo] values(5960, 'Marstal');
Insert into [dbo].[tblPostNo] values(5970, 'Ærøskøbing');
Insert into [dbo].[tblPostNo] values(5985, 'Søby Ærø');
Insert into [dbo].[tblPostNo] values(6000, 'Kolding');
Insert into [dbo].[tblPostNo] values(6040, 'Egtved');
Insert into [dbo].[tblPostNo] values(6051, 'Almind');
Insert into [dbo].[tblPostNo] values(6052, 'Viuf');
Insert into [dbo].[tblPostNo] values(6064, 'Jordrup');
Insert into [dbo].[tblPostNo] values(6070, 'Christiansfeld');
Insert into [dbo].[tblPostNo] values(6091, 'Bjert');
Insert into [dbo].[tblPostNo] values(6092, 'Sønder Stenderup');
Insert into [dbo].[tblPostNo] values(6093, 'Sjølund');
Insert into [dbo].[tblPostNo] values(6094, 'Hejls');
Insert into [dbo].[tblPostNo] values(6100, 'Haderslev');
Insert into [dbo].[tblPostNo] values(6200, 'Aabenraa');
Insert into [dbo].[tblPostNo] values(6230, 'Rødekro');
Insert into [dbo].[tblPostNo] values(6240, 'Løgumkloster');
Insert into [dbo].[tblPostNo] values(6261, 'Bredebro');
Insert into [dbo].[tblPostNo] values(6270, 'Tønder');
Insert into [dbo].[tblPostNo] values(6280, 'Højer');
Insert into [dbo].[tblPostNo] values(6300, 'Gråsten');
Insert into [dbo].[tblPostNo] values(6310, 'Broager');
Insert into [dbo].[tblPostNo] values(6320, 'Egernsund');
Insert into [dbo].[tblPostNo] values(6330, 'Padborg');
Insert into [dbo].[tblPostNo] values(6340, 'Kruså');
Insert into [dbo].[tblPostNo] values(6360, 'Tinglev');
Insert into [dbo].[tblPostNo] values(6372, 'Bylderup-Bov');
Insert into [dbo].[tblPostNo] values(6392, 'Bolderslev');
Insert into [dbo].[tblPostNo] values(6400, 'Sønderborg');
Insert into [dbo].[tblPostNo] values(6430, 'Nordborg');
Insert into [dbo].[tblPostNo] values(6440, 'Augustenborg');
Insert into [dbo].[tblPostNo] values(6470, 'Sydals');
Insert into [dbo].[tblPostNo] values(6500, 'Vojens');
Insert into [dbo].[tblPostNo] values(6510, 'Gram');
Insert into [dbo].[tblPostNo] values(6520, 'Toftlund');
Insert into [dbo].[tblPostNo] values(6534, 'Agerskov');
Insert into [dbo].[tblPostNo] values(6535, 'Branderup Jylland');
Insert into [dbo].[tblPostNo] values(6541, 'Bevtoft');
Insert into [dbo].[tblPostNo] values(6560, 'Sommersted');
Insert into [dbo].[tblPostNo] values(6580, 'Vamdrup');
Insert into [dbo].[tblPostNo] values(6600, 'Vejen');
Insert into [dbo].[tblPostNo] values(6621, 'Gesten');
Insert into [dbo].[tblPostNo] values(6622, 'Bække');
Insert into [dbo].[tblPostNo] values(6623, 'Vorbasse');
Insert into [dbo].[tblPostNo] values(6630, 'Rødding');
Insert into [dbo].[tblPostNo] values(6640, 'Lunderskov');
Insert into [dbo].[tblPostNo] values(6650, 'Brørup');
Insert into [dbo].[tblPostNo] values(6660, 'Lintrup');
Insert into [dbo].[tblPostNo] values(6670, 'Holsted');
Insert into [dbo].[tblPostNo] values(6682, 'Hovborg');
Insert into [dbo].[tblPostNo] values(6683, 'Føvling');
Insert into [dbo].[tblPostNo] values(6690, 'Gørding');
Insert into [dbo].[tblPostNo] values(6700, 'Esbjerg');
Insert into [dbo].[tblPostNo] values(6705, 'Esbjerg Ø');
Insert into [dbo].[tblPostNo] values(6710, 'Esbjerg V');
Insert into [dbo].[tblPostNo] values(6715, 'Esbjerg N');
Insert into [dbo].[tblPostNo] values(6720, 'Fanø');
Insert into [dbo].[tblPostNo] values(6731, 'Tjæreborg');
Insert into [dbo].[tblPostNo] values(6740, 'Bramming');
Insert into [dbo].[tblPostNo] values(6752, 'Glejbjerg');
Insert into [dbo].[tblPostNo] values(6753, 'Agerbæk');
Insert into [dbo].[tblPostNo] values(6760, 'Ribe');
Insert into [dbo].[tblPostNo] values(6771, 'Gredstedbro');
Insert into [dbo].[tblPostNo] values(6780, 'Skærbæk');
Insert into [dbo].[tblPostNo] values(6792, 'Rømø');
Insert into [dbo].[tblPostNo] values(6800, 'Varde');
Insert into [dbo].[tblPostNo] values(6818, 'Årre');
Insert into [dbo].[tblPostNo] values(6823, 'Ansager');
Insert into [dbo].[tblPostNo] values(6830, 'Nørre Nebel');
Insert into [dbo].[tblPostNo] values(6840, 'Oksbøl');
Insert into [dbo].[tblPostNo] values(6851, 'Janderup Vestjylland');
Insert into [dbo].[tblPostNo] values(6852, 'Billum');
Insert into [dbo].[tblPostNo] values(6853, 'Vejers Strand');
Insert into [dbo].[tblPostNo] values(6854, 'Henne');
Insert into [dbo].[tblPostNo] values(6855, 'Outrup');
Insert into [dbo].[tblPostNo] values(6857, 'Blåvand');
Insert into [dbo].[tblPostNo] values(6862, 'Tistrup');
Insert into [dbo].[tblPostNo] values(6870, 'Ølgod');
Insert into [dbo].[tblPostNo] values(6880, 'Tarm');
Insert into [dbo].[tblPostNo] values(6893, 'Hemmet');
Insert into [dbo].[tblPostNo] values(6900, 'Skjern');
Insert into [dbo].[tblPostNo] values(6920, 'Videbæk');
Insert into [dbo].[tblPostNo] values(6933, 'Kibæk');
Insert into [dbo].[tblPostNo] values(6940, 'Lem St.');
Insert into [dbo].[tblPostNo] values(6950, 'Ringkøbing');
Insert into [dbo].[tblPostNo] values(6960, 'Hvide Sande');
Insert into [dbo].[tblPostNo] values(6971, 'Spjald');
Insert into [dbo].[tblPostNo] values(6973, 'Ørnhøj');
Insert into [dbo].[tblPostNo] values(6980, 'Tim');
Insert into [dbo].[tblPostNo] values(6990, 'Ulfborg');
Insert into [dbo].[tblPostNo] values(7000, 'Fredericia');
Insert into [dbo].[tblPostNo] values(7007, 'Fredericia Sydjyllands Postcenter');
Insert into [dbo].[tblPostNo] values(7080, 'Børkop');
Insert into [dbo].[tblPostNo] values(7100, 'Vejle');
Insert into [dbo].[tblPostNo] values(7120, 'Vejle Øst');
Insert into [dbo].[tblPostNo] values(7130, 'Juelsminde');
Insert into [dbo].[tblPostNo] values(7140, 'Stouby');
Insert into [dbo].[tblPostNo] values(7150, 'Barrit');
Insert into [dbo].[tblPostNo] values(7160, 'Tørring');
Insert into [dbo].[tblPostNo] values(7171, 'Uldum');
Insert into [dbo].[tblPostNo] values(7173, 'Vonge');
Insert into [dbo].[tblPostNo] values(7182, 'Bredsten');
Insert into [dbo].[tblPostNo] values(7183, 'Randbøl');
Insert into [dbo].[tblPostNo] values(7184, 'Vandel');
Insert into [dbo].[tblPostNo] values(7190, 'Billund');
Insert into [dbo].[tblPostNo] values(7200, 'Grindsted');
Insert into [dbo].[tblPostNo] values(7250, 'Hejnsvig');
Insert into [dbo].[tblPostNo] values(7260, 'Sønder Omme');
Insert into [dbo].[tblPostNo] values(7270, 'Stakroge');
Insert into [dbo].[tblPostNo] values(7280, 'Sønder Felding');
Insert into [dbo].[tblPostNo] values(7300, 'Jelling');
Insert into [dbo].[tblPostNo] values(7321, 'Gadbjerg');
Insert into [dbo].[tblPostNo] values(7323, 'Give');
Insert into [dbo].[tblPostNo] values(7330, 'Brande');
Insert into [dbo].[tblPostNo] values(7361, 'Ejstrupholm');
Insert into [dbo].[tblPostNo] values(7362, 'Hampen');
Insert into [dbo].[tblPostNo] values(7400, 'Herning');
Insert into [dbo].[tblPostNo] values(7401, 'Herning Vestjyllands Postcenter');
Insert into [dbo].[tblPostNo] values(7430, 'Ikast');
Insert into [dbo].[tblPostNo] values(7441, 'Bording');
Insert into [dbo].[tblPostNo] values(7442, 'Engesvang');
Insert into [dbo].[tblPostNo] values(7451, 'Sunds');
Insert into [dbo].[tblPostNo] values(7470, 'Karup Jylland');
Insert into [dbo].[tblPostNo] values(7480, 'Vildbjerg');
Insert into [dbo].[tblPostNo] values(7490, 'Aulum');
Insert into [dbo].[tblPostNo] values(7500, 'Holstebro');
Insert into [dbo].[tblPostNo] values(7540, 'Haderup');
Insert into [dbo].[tblPostNo] values(7550, 'Sørvad');
Insert into [dbo].[tblPostNo] values(7560, 'Hjerm');
Insert into [dbo].[tblPostNo] values(7570, 'Vemb');
Insert into [dbo].[tblPostNo] values(7600, 'Struer');
Insert into [dbo].[tblPostNo] values(7620, 'Lemvig');
Insert into [dbo].[tblPostNo] values(7650, 'Bøvlingbjerg');
Insert into [dbo].[tblPostNo] values(7660, 'Bækmarksbro');
Insert into [dbo].[tblPostNo] values(7673, 'Harboøre');
Insert into [dbo].[tblPostNo] values(7680, 'Thyborøn');
Insert into [dbo].[tblPostNo] values(7700, 'Thisted');
Insert into [dbo].[tblPostNo] values(7730, 'Hanstholm');
Insert into [dbo].[tblPostNo] values(7741, 'Frøstrup');
Insert into [dbo].[tblPostNo] values(7742, 'Vesløs');
Insert into [dbo].[tblPostNo] values(7752, 'Snedsted');
Insert into [dbo].[tblPostNo] values(7755, 'Bedsted Thy');
Insert into [dbo].[tblPostNo] values(7760, 'Hurup Thy');
Insert into [dbo].[tblPostNo] values(7770, 'Vestervig');
Insert into [dbo].[tblPostNo] values(7790, 'Thyholm');
Insert into [dbo].[tblPostNo] values(7800, 'Skive');
Insert into [dbo].[tblPostNo] values(7830, 'Vinderup');
Insert into [dbo].[tblPostNo] values(7840, 'Højslev');
Insert into [dbo].[tblPostNo] values(7850, 'Stoholm Jylland');
Insert into [dbo].[tblPostNo] values(7860, 'Spøttrup');
Insert into [dbo].[tblPostNo] values(7870, 'Roslev');
Insert into [dbo].[tblPostNo] values(7884, 'Fur');
Insert into [dbo].[tblPostNo] values(7900, 'Nykøbing Mors');
Insert into [dbo].[tblPostNo] values(7950, 'Erslev');
Insert into [dbo].[tblPostNo] values(7960, 'Karby');
Insert into [dbo].[tblPostNo] values(7970, 'Redsted Mors');
Insert into [dbo].[tblPostNo] values(7980, 'Vils');
Insert into [dbo].[tblPostNo] values(7990, 'Øster Assels');
Insert into [dbo].[tblPostNo] values(8000, 'Århus C');
Insert into [dbo].[tblPostNo] values(8011, 'Århus C Østjyllands Postcenter');
Insert into [dbo].[tblPostNo] values(8200, 'Århus N');
Insert into [dbo].[tblPostNo] values(8210, 'Århus V');
Insert into [dbo].[tblPostNo] values(8220, 'Brabrand');
Insert into [dbo].[tblPostNo] values(8230, 'Åbyhøj');
Insert into [dbo].[tblPostNo] values(8240, 'Risskov');
Insert into [dbo].[tblPostNo] values(8245, 'Risskov Ø Østjyllands Postcenter');
Insert into [dbo].[tblPostNo] values(8250, 'Egå');
Insert into [dbo].[tblPostNo] values(8260, 'Viby Jylland');
Insert into [dbo].[tblPostNo] values(8270, 'Højbjerg');
Insert into [dbo].[tblPostNo] values(8300, 'Odder');
Insert into [dbo].[tblPostNo] values(8305, 'Samsø');
Insert into [dbo].[tblPostNo] values(8310, 'Tranbjerg Jylland');
Insert into [dbo].[tblPostNo] values(8320, 'Mårslet');
Insert into [dbo].[tblPostNo] values(8330, 'Beder');
Insert into [dbo].[tblPostNo] values(8340, 'Malling');
Insert into [dbo].[tblPostNo] values(8350, 'Hundslund');
Insert into [dbo].[tblPostNo] values(8355, 'Solbjerg');
Insert into [dbo].[tblPostNo] values(8361, 'Hasselager');
Insert into [dbo].[tblPostNo] values(8362, 'Hørning');
Insert into [dbo].[tblPostNo] values(8370, 'Hadsten');
Insert into [dbo].[tblPostNo] values(8380, 'Trige');
Insert into [dbo].[tblPostNo] values(8381, 'Tilst');
Insert into [dbo].[tblPostNo] values(8382, 'Hinnerup');
Insert into [dbo].[tblPostNo] values(8400, 'Ebeltoft');
Insert into [dbo].[tblPostNo] values(8410, 'Rønde');
Insert into [dbo].[tblPostNo] values(8420, 'Knebel');
Insert into [dbo].[tblPostNo] values(8444, 'Balle');
Insert into [dbo].[tblPostNo] values(8450, 'Hammel');
Insert into [dbo].[tblPostNo] values(8462, 'Harlev Jylland');
Insert into [dbo].[tblPostNo] values(8464, 'Galten');
Insert into [dbo].[tblPostNo] values(8471, 'Sabro');
Insert into [dbo].[tblPostNo] values(8472, 'Sporup');
Insert into [dbo].[tblPostNo] values(8500, 'Grenaa');
Insert into [dbo].[tblPostNo] values(8520, 'Lystrup');
Insert into [dbo].[tblPostNo] values(8530, 'Hjortshøj');
Insert into [dbo].[tblPostNo] values(8541, 'Skødstrup');
Insert into [dbo].[tblPostNo] values(8543, 'Hornslet');
Insert into [dbo].[tblPostNo] values(8544, 'Mørke');
Insert into [dbo].[tblPostNo] values(8550, 'Ryomgård');
Insert into [dbo].[tblPostNo] values(8560, 'Kolind');
Insert into [dbo].[tblPostNo] values(8570, 'Trustrup');
Insert into [dbo].[tblPostNo] values(8581, 'Nimtofte');
Insert into [dbo].[tblPostNo] values(8585, 'Glesborg');
Insert into [dbo].[tblPostNo] values(8586, 'Ørum Djurs');
Insert into [dbo].[tblPostNo] values(8592, 'Anholt');
Insert into [dbo].[tblPostNo] values(8600, 'Silkeborg');
Insert into [dbo].[tblPostNo] values(8620, 'Kjellerup');
Insert into [dbo].[tblPostNo] values(8632, 'Lemming');
Insert into [dbo].[tblPostNo] values(8641, 'Sorring');
Insert into [dbo].[tblPostNo] values(8643, 'Ans By');
Insert into [dbo].[tblPostNo] values(8653, 'Them');
Insert into [dbo].[tblPostNo] values(8654, 'Bryrup');
Insert into [dbo].[tblPostNo] values(8660, 'Skanderborg');
Insert into [dbo].[tblPostNo] values(8670, 'Låsby');
Insert into [dbo].[tblPostNo] values(8680, 'Ry');
Insert into [dbo].[tblPostNo] values(8700, 'Horsens');
Insert into [dbo].[tblPostNo] values(8721, 'Daugård');
Insert into [dbo].[tblPostNo] values(8722, 'Hedensted');
Insert into [dbo].[tblPostNo] values(8723, 'Løsning');
Insert into [dbo].[tblPostNo] values(8732, 'Hovedgård');
Insert into [dbo].[tblPostNo] values(8740, 'Brædstrup');
Insert into [dbo].[tblPostNo] values(8751, 'Gedved');
Insert into [dbo].[tblPostNo] values(8752, 'Østbirk');
Insert into [dbo].[tblPostNo] values(8762, 'Flemming');
Insert into [dbo].[tblPostNo] values(8763, 'Rask Mølle');
Insert into [dbo].[tblPostNo] values(8765, 'Klovborg');
Insert into [dbo].[tblPostNo] values(8766, 'Nørre Snede');
Insert into [dbo].[tblPostNo] values(8781, 'Stenderup');
Insert into [dbo].[tblPostNo] values(8783, 'Hornsyld');
Insert into [dbo].[tblPostNo] values(8800, 'Viborg');
Insert into [dbo].[tblPostNo] values(8830, 'Tjele');
Insert into [dbo].[tblPostNo] values(8831, 'Løgstrup');
Insert into [dbo].[tblPostNo] values(8832, 'Skals');
Insert into [dbo].[tblPostNo] values(8840, 'Rødkærsbro');
Insert into [dbo].[tblPostNo] values(8850, 'Bjerringbro');
Insert into [dbo].[tblPostNo] values(8860, 'Ulstrup');
Insert into [dbo].[tblPostNo] values(8870, 'Langå');
Insert into [dbo].[tblPostNo] values(8881, 'Thorsø');
Insert into [dbo].[tblPostNo] values(8882, 'Fårvang');
Insert into [dbo].[tblPostNo] values(8883, 'Gjern');
Insert into [dbo].[tblPostNo] values(8900, 'Randers');
Insert into [dbo].[tblPostNo] values(8950, 'Ørsted');
Insert into [dbo].[tblPostNo] values(8961, 'Allingåbro');
Insert into [dbo].[tblPostNo] values(8963, 'Auning');
Insert into [dbo].[tblPostNo] values(8970, 'Havndal');
Insert into [dbo].[tblPostNo] values(8981, 'Spentrup');
Insert into [dbo].[tblPostNo] values(8983, 'Gjerlev Jylland');
Insert into [dbo].[tblPostNo] values(8990, 'Fårup');
Insert into [dbo].[tblPostNo] values(9000, 'Aalborg');
Insert into [dbo].[tblPostNo] values(9020, 'Aalborg Nordjyllands Postcenter');
Insert into [dbo].[tblPostNo] values(9200, 'Aalborg SV');
Insert into [dbo].[tblPostNo] values(9210, 'Aalborg SØ');
Insert into [dbo].[tblPostNo] values(9220, 'Aalborg Øst');
Insert into [dbo].[tblPostNo] values(9230, 'Svenstrup Jylland');
Insert into [dbo].[tblPostNo] values(9240, 'Nibe');
Insert into [dbo].[tblPostNo] values(9260, 'Gistrup');
Insert into [dbo].[tblPostNo] values(9270, 'Klarup');
Insert into [dbo].[tblPostNo] values(9280, 'Storvorde');
Insert into [dbo].[tblPostNo] values(9293, 'Kongerslev');
Insert into [dbo].[tblPostNo] values(9300, 'Sæby');
Insert into [dbo].[tblPostNo] values(9310, 'Vodskov');
Insert into [dbo].[tblPostNo] values(9320, 'Hjallerup');
Insert into [dbo].[tblPostNo] values(9330, 'Dronninglund');
Insert into [dbo].[tblPostNo] values(9340, 'Asaa');
Insert into [dbo].[tblPostNo] values(9352, 'Dybvad');
Insert into [dbo].[tblPostNo] values(9362, 'Gandrup');
Insert into [dbo].[tblPostNo] values(9370, 'Hals');
Insert into [dbo].[tblPostNo] values(9380, 'Vestbjerg');
Insert into [dbo].[tblPostNo] values(9381, 'Sulsted');
Insert into [dbo].[tblPostNo] values(9382, 'Tylstrup');
Insert into [dbo].[tblPostNo] values(9400, 'Nørresundby');
Insert into [dbo].[tblPostNo] values(9430, 'Vadum');
Insert into [dbo].[tblPostNo] values(9440, 'Aabybro');
Insert into [dbo].[tblPostNo] values(9460, 'Brovst');
Insert into [dbo].[tblPostNo] values(9480, 'Løkken');
Insert into [dbo].[tblPostNo] values(9490, 'Pandrup');
Insert into [dbo].[tblPostNo] values(9492, 'Blokhus');
Insert into [dbo].[tblPostNo] values(9493, 'Saltum');
Insert into [dbo].[tblPostNo] values(9500, 'Hobro');
Insert into [dbo].[tblPostNo] values(9510, 'Arden');
Insert into [dbo].[tblPostNo] values(9520, 'Skørping');
Insert into [dbo].[tblPostNo] values(9530, 'Støvring');
Insert into [dbo].[tblPostNo] values(9541, 'Suldrup');
Insert into [dbo].[tblPostNo] values(9550, 'Mariager');
Insert into [dbo].[tblPostNo] values(9560, 'Hadsund');
Insert into [dbo].[tblPostNo] values(9574, 'Bælum');
Insert into [dbo].[tblPostNo] values(9575, 'Terndrup');
Insert into [dbo].[tblPostNo] values(9600, 'Aars');
Insert into [dbo].[tblPostNo] values(9610, 'Nørager');
Insert into [dbo].[tblPostNo] values(9620, 'Aalestrup');
Insert into [dbo].[tblPostNo] values(9631, 'Gedsted');
Insert into [dbo].[tblPostNo] values(9632, 'Møldrup');
Insert into [dbo].[tblPostNo] values(9640, 'Farsø');
Insert into [dbo].[tblPostNo] values(9670, 'Løgstør');
Insert into [dbo].[tblPostNo] values(9681, 'Ranum');
Insert into [dbo].[tblPostNo] values(9690, 'Fjerritslev');
Insert into [dbo].[tblPostNo] values(9700, 'Brønderslev');
Insert into [dbo].[tblPostNo] values(9740, 'Jerslev Jylland');
Insert into [dbo].[tblPostNo] values(9750, 'Østervrå');
Insert into [dbo].[tblPostNo] values(9760, 'Vrå');
Insert into [dbo].[tblPostNo] values(9800, 'Hjørring');
Insert into [dbo].[tblPostNo] values(9830, 'Tårs');
Insert into [dbo].[tblPostNo] values(9850, 'Hirtshals');
Insert into [dbo].[tblPostNo] values(9870, 'Sindal');
Insert into [dbo].[tblPostNo] values(9881, 'Bindslev');
Insert into [dbo].[tblPostNo] values(9900, 'Frederikshavn');
Insert into [dbo].[tblPostNo] values(9940, 'Læsø');
Insert into [dbo].[tblPostNo] values(9970, 'Strandby');
Insert into [dbo].[tblPostNo] values(9981, 'Jerup');
Insert into [dbo].[tblPostNo] values(9982, 'Ålbæk');
Insert into [dbo].[tblPostNo] values(9990, 'Skagen');
GO